### ISSUE TITLE
[Bug]: Discord user has a requiredRole but cannot join due to not having the requiredRole

### ISSUE THREAD

**Issue by RandomGgames** [ErdbeerbaerLP/Discord-Integration-Fabric#11]
See https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/issues/483

Also, the mod on CurseForge links issues and Wiki to the Forge version instead of into this Fabric version.

**Comment by Lgmrszd** [comment]
Can confirm. Same issue happened to other players but not me while I was testing it.
Players are able to link accounts easily but unable to join the server despite having the role needed.
Checked `DiscordIntegration-Data/LinkedPlayers.json` and the players link is present here, seems that mod somehow fails to check if role is present.

**Comment by Lgmrszd** [comment]
I noticed that I were able to join just fine, but not with another account with just required role.
What is strange though, is that linking accounts works, but it requires having role as well.
I noticed that in `/link` Discord command, [roles are compared by IDs](https://github.com/ErdbeerbaerLP/DiscordIntegration-Core/blob/e96fead1073bbcaac93e0710800d2a72c0366bf5/src/main/java/de/erdbeerbaerlp/dcintegration/common/discordCommands/CommandLink.java#L41), while in `canPlayerJoin` function, [roles are compared as objects](https://github.com/ErdbeerbaerLP/DiscordIntegration-Core/blob/947b6cd85588a6e81d8a2c7cf86a48957d2af1f3/src/main/java/de/erdbeerbaerlp/dcintegration/common/Discord.java#L197). Could it be that `canPlayerJoin` is actually malfunctioning, and for some reason actually returning true for other roles?

**Comment by RandomGgames** [comment]
I noticed in the server console that it was saying the getRoles function was not working, or something along those lines.

**Comment by Tobias-Jung-DHBW** [comment]
Dirty Fixed by setting
requiredRoles = [    ]
and just allow in the one channel where the slash commands are allowed for only that role... 
But had the same issue

**Comment by intcreator** [comment]
nice workaround! I'm also running into this issue. I'm attempting to debug it but I'm having a hard time setting up the mod repo because the README is basically empty and the "for developers" page is still blank

**Comment by dAKirby309** [comment]
> Dirty Fixed by setting requiredRoles = [ ] and just allow in the one channel where the slash commands are allowed for only that role... But had the same issue

@Tobias-Jung-DHBW I'm not sure what this dirty fix means, exactly. Based on what you said, I added my required role ID to `requiredRoles = [ "roleID" ]` and I made it where that role could only do Discord application commands and `/link` in the channel I want used for linking but the same issue is happening.

**Comment by ErdbeerbaerLP** [comment]
Should be fixed in 2.6.4
(1.19.3,4 and 1.18.2 will release later today)

**Comment by dAKirby309** [comment]
Very-much agreed  I am using 1.19 and it would be fantastic if this feature was fixed for that version.
