### ISSUE TITLE
Player timing out causes all future leave messages from user to be treated as timeouts

### ISSUE THREAD

**Issue by LilyRose2798** [ErdbeerbaerLP/Discord-Integration-Fabric#6]
I've noticed that if a user disconnects via timeout that any time they leave the server normally after that the messages are all shown in discord as "___ timed out!"

For instance, here are the server logs of a player who timed out twice, and then left normally the third time they disconnected:
![image](https://user-images.githubusercontent.com/1974590/148641566-07dd6989-80ed-41ad-af09-00ae96d7c86b.png)

But this is what the discord bot sent (ignore the time difference for the hours, it's just different timezones):
![image](https://user-images.githubusercontent.com/1974590/148641426-b023e5bb-c8ee-4aab-80f0-c38eefb82c7a.png)

From looking at the code, it seems that the `timeouts` array might not have the player being removed correctly. Maybe there needs to be a mixin that removes a player from the timeout list upon connecting as well as the existing disconnect mixin, as it seems just removing from the list after sending the timeout message isn't serving that purpose as expected.

**Comment by ErdbeerbaerLP** [comment]
There was already an fix PR to the forge version, will be implementing a semilar fix to fabric, too

( https://github.com/ErdbeerbaerLP/DiscordIntegration-Forge/pull/367 )
