### ISSUE TITLE
Curseforge page for this project has links to the forge version of the repository

### ISSUE THREAD

**Issue by LilyRose2798** [ErdbeerbaerLP/Discord-Integration-Fabric#7]
The issues and wiki links on the [Curseforge listing](https://www.curseforge.com/minecraft/mc-mods/dcintegration-fabric) for this mod link to the forge version rather than fabric.

**Comment by ErdbeerbaerLP** [comment]
Yes, that's intentional.

Issues because I wanted to have them cantralized at one place and on the forge project were all of them, so I decided to collect them there

Wiki is same for all so why making an new one for all versions?
